# Generated by Django 3.0.8 on 2021-08-28 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=25)),
                ('fiscal_number', models.CharField(max_length=20)),
                ('contract', models.CharField(max_length=25)),
                ('start_date', models.CharField(max_length=20)),
                ('end_date', models.CharField(max_length=20)),
                ('comments', models.CharField(max_length=500)),
                ('doc_path', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'ExtractedData',
                'verbose_name_plural': 'ExtractedDatas',
            },
        ),
    ]
