# Generated by Django 3.0.8 on 2021-08-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extract', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extracteddata',
            name='comments',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='extracteddata',
            name='contract',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='extracteddata',
            name='doc_path',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='extracteddata',
            name='end_date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='extracteddata',
            name='fiscal_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='extracteddata',
            name='start_date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='extracteddata',
            name='vendor_name',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
